M48
; DRILL file {KiCad 9.0.0} date 2025-07-20T20:17:57+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-20T20:17:57+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X166.545Y-94.948
T2
X160.545Y-94.948
T3
X188.52Y-70.159
X188.52Y-95.149
T4
X121.8Y-96.8
X206.8Y-68.2
X206.8Y-96.8
M30
